const fs = require('fs-extra')
if (fs.existsSync('.env')) require('dotenv').config({ path: __dirname+'/.env' })


//═══════[Required Variables]════════\\
global.audio= "" ;  
global.video= "" ;
global.port =process.env.PORT
global.appUrl=process.env.APP_URL || ""                       // put your app url here,
global.email ="samsamsun789@gmail.com"
global.location="Lahore,Pakistan."
global.mongodb= process.env.MONGODB_URI || "mongodb+srv://Dj302:<password>@dj302.i5u8nrs.mongodb.net/"
global.allowJids= process.env.ALLOW_JID || "null" 
global.blockJids= process.env.BLOCK_JID || "120363023983262391@g.us"
global.DATABASE_URI = process.env.DATABASE_URL || ""

global.timezone= process.env.TZ || process.env.TIME_ZONE || "Asia/Karachi";
global.github=process.env.GITHUB|| "https://github.com/SuhailTechInfo/Suhail-Md";
global.gurl  =process.env.GURL  || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643";
global.website=process.env.GURL || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643" ; 
global.THUMB_IMAGE = process.env.THUMB_IMAGE || process.env.IMAGE || "https://telegra.ph/file/d5b1c3544fedc23e11a06.jpg" ; // SET LOGO FOR IMAGE 



global.devs = "923184474176" // Developer Contact
global.sudo = process.env.SUDO ? process.env.SUDO.replace(/[\s+]/g, '') : "null";
global.owner= process.env.OWNER_NUMBER ? process.env.OWNER_NUMBER.replace(/[\s+]/g, '') : "923184474176";




//========================= [ BOT SETTINGS ] =========================\\
global.style = process.env.STYLE   || '5',  // put '1' to "5" here to check bot styles
global.flush = process.env.FLUSH   || "false"; // Make it "true" if bot not responed
global.gdbye = process.env.GOODBYE || "false"; 
global.wlcm  = process.env.WELCOME || "true";  // Make it "false" for disable WELCOME 

global.warncount = process.env.WARN_COUNT || 3,
global.disablepm = process.env.DISABLE_PM || "false",
global.MsgsInLog = process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
global.userImages= process.env.USER_IMAGES|| "text",
global.waPresence= process.env.WAPRESENCE ||  "set according to your need" ; // 'unavailable' | 'available' | 'composing' | 'recording' | 'paused'


//========================= [ AUTO READ MSGS & CMDS ] =========================\\
global.readcmds = process.env.READ_COMMAND || "false"
global.readmessage = process.env.READ_MESSAGE || "false"
global.readmessagefrom = process.env.READ_MESSAGE_FROM || "923184474176,923xxxxxxxx";


//========================= [ AUTO SAVE & READ STATUS ] =========================\\
global.read_status = process.env.AUTO_READ_STATUS || "false"
global.save_status = process.env.AUTO_SAVE_STATUS || "false"
global.save_status_from =  process.env.SAVE_STATUS_FROM  || "null,923xxxxxxxx";
global.read_status_from =  process.env.READ_STATUS_FROM  ||  "923184474176,923xxxxxxxx";

global.api_smd = "https://api-smd-1.vercel.app"
global.scan = "https://suhail-md-vtsf.onrender.com/";

module.exports = {

  menu: process.env.MENU || "", /**  Available @MENU @Schemes 1: Aztec_Md, 2: A17_Md, 3: Suhail-Md Default ---------- If Not Choose then it Randomely Pic One Of Them Each time **/

  HANDLERS: process.env.PREFIX  || ".",
  BRANCH  : process.env.BRANCH  || "main",
  VERSION : process.env.VERSION || "V.1.2.8",
  caption : process.env.CAPTION || "©sᴜʜᴀɪʟ²²¹-ᴍᴅ" , // ```『 ᴘᴏᴡᴇʀᴇᴅ ʙʏ sᴜʜᴀɪʟ²²¹-ᴍᴅ 』```", //*『sᴜʙsᴄʀɪʙᴇ • sᴜʜᴀɪʟ ᴛᴇᴄʜ』*\n youtube.com/@suhailtechinfo0"),
 
  author : process.env.PACK_AUTHER|| "Suhail-MD",
  packname: process.env.PACK_NAME || "♥️",
  botname : process.env.BOT_NAME  || "sᴜʜᴀɪʟ-ᴍᴅ",
  ownername:process.env.OWNER_NAME|| "It'x Suhail",

  sessionName:process.env.SESSION_ID || "SUHAIL_04_51_05_03_ewogICJjcmVkcy5qc29uIjogIntcbiAgXCJub2lzZUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMjA4LFxuICAgICAgICA5MyxcbiAgICAgICAgMjMwLFxuICAgICAgICA1NyxcbiAgICAgICAgMjMsXG4gICAgICAgIDIzOCxcbiAgICAgICAgNjIsXG4gICAgICAgIDIyNyxcbiAgICAgICAgMTMyLFxuICAgICAgICAyMDYsXG4gICAgICAgIDI3LFxuICAgICAgICAyNDYsXG4gICAgICAgIDI0NyxcbiAgICAgICAgMTA0LFxuICAgICAgICAzOSxcbiAgICAgICAgOTMsXG4gICAgICAgIDE4NixcbiAgICAgICAgNDUsXG4gICAgICAgIDIzMyxcbiAgICAgICAgMjQ2LFxuICAgICAgICAyMixcbiAgICAgICAgMjQyLFxuICAgICAgICA3NixcbiAgICAgICAgMjM2LFxuICAgICAgICA1NyxcbiAgICAgICAgMTc3LFxuICAgICAgICA5NSxcbiAgICAgICAgNzMsXG4gICAgICAgIDMxLFxuICAgICAgICAyMzEsXG4gICAgICAgIDE5OCxcbiAgICAgICAgOTNcbiAgICAgIF1cbiAgICB9LFxuICAgIFwicHVibGljXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMjEwLFxuICAgICAgICA3NSxcbiAgICAgICAgMjYsXG4gICAgICAgIDk2LFxuICAgICAgICAyNDksXG4gICAgICAgIDE0MixcbiAgICAgICAgMTc2LFxuICAgICAgICAxMTUsXG4gICAgICAgIDE0NixcbiAgICAgICAgMTI1LFxuICAgICAgICAxMjAsXG4gICAgICAgIDE5MyxcbiAgICAgICAgMTY0LFxuICAgICAgICA2NixcbiAgICAgICAgMTIzLFxuICAgICAgICAxOCxcbiAgICAgICAgMTcyLFxuICAgICAgICAyMzEsXG4gICAgICAgIDQwLFxuICAgICAgICAyMjQsXG4gICAgICAgIDE2MSxcbiAgICAgICAgMyxcbiAgICAgICAgMjI5LFxuICAgICAgICAyMixcbiAgICAgICAgMzcsXG4gICAgICAgIDU2LFxuICAgICAgICA3NCxcbiAgICAgICAgNixcbiAgICAgICAgMTM1LFxuICAgICAgICAyMzEsXG4gICAgICAgIDYxLFxuICAgICAgICA4XG4gICAgICBdXG4gICAgfVxuICB9LFxuICBcInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyXCI6IHtcbiAgICBcInByaXZhdGVcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAxNjgsXG4gICAgICAgIDEwLFxuICAgICAgICAxMjgsXG4gICAgICAgIDM1LFxuICAgICAgICAyNTUsXG4gICAgICAgIDExMixcbiAgICAgICAgNzgsXG4gICAgICAgIDgsXG4gICAgICAgIDE1NyxcbiAgICAgICAgMTc4LFxuICAgICAgICA4OCxcbiAgICAgICAgODgsXG4gICAgICAgIDYyLFxuICAgICAgICAyMTQsXG4gICAgICAgIDIwNixcbiAgICAgICAgMjI2LFxuICAgICAgICAxMjcsXG4gICAgICAgIDE4NCxcbiAgICAgICAgMTI3LFxuICAgICAgICA0MyxcbiAgICAgICAgNDQsXG4gICAgICAgIDIxNSxcbiAgICAgICAgOTYsXG4gICAgICAgIDE2NixcbiAgICAgICAgMjUxLFxuICAgICAgICA3MyxcbiAgICAgICAgMjMxLFxuICAgICAgICAxNTcsXG4gICAgICAgIDEyOCxcbiAgICAgICAgODgsXG4gICAgICAgIDE4NyxcbiAgICAgICAgOTlcbiAgICAgIF1cbiAgICB9LFxuICAgIFwicHVibGljXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMjcsXG4gICAgICAgIDc1LFxuICAgICAgICAxMTIsXG4gICAgICAgIDE1OSxcbiAgICAgICAgMTY1LFxuICAgICAgICA5NixcbiAgICAgICAgNDAsXG4gICAgICAgIDU3LFxuICAgICAgICAxLFxuICAgICAgICAxNDYsXG4gICAgICAgIDI0NyxcbiAgICAgICAgMixcbiAgICAgICAgNixcbiAgICAgICAgNjUsXG4gICAgICAgIDc1LFxuICAgICAgICAxMDEsXG4gICAgICAgIDc3LFxuICAgICAgICA0LFxuICAgICAgICAxNDEsXG4gICAgICAgIDE4NyxcbiAgICAgICAgMTUwLFxuICAgICAgICA1MCxcbiAgICAgICAgNTMsXG4gICAgICAgIDI4LFxuICAgICAgICAxNTQsXG4gICAgICAgIDM0LFxuICAgICAgICAyNDksXG4gICAgICAgIDI1NSxcbiAgICAgICAgNjQsXG4gICAgICAgIDIzNSxcbiAgICAgICAgMjEwLFxuICAgICAgICAyOFxuICAgICAgXVxuICAgIH1cbiAgfSxcbiAgXCJzaWduZWRJZGVudGl0eUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMjA4LFxuICAgICAgICAxOTgsXG4gICAgICAgIDIyNyxcbiAgICAgICAgMTQsXG4gICAgICAgIDE1NyxcbiAgICAgICAgMTA0LFxuICAgICAgICA1NCxcbiAgICAgICAgNDIsXG4gICAgICAgIDEyMSxcbiAgICAgICAgMTUzLFxuICAgICAgICA4LFxuICAgICAgICAyMjIsXG4gICAgICAgIDEzMixcbiAgICAgICAgNzksXG4gICAgICAgIDI0LFxuICAgICAgICA1MyxcbiAgICAgICAgMTE3LFxuICAgICAgICA0NixcbiAgICAgICAgMTAxLFxuICAgICAgICAyMjAsXG4gICAgICAgIDY0LFxuICAgICAgICAxMTYsXG4gICAgICAgIDc1LFxuICAgICAgICAxMjQsXG4gICAgICAgIDUzLFxuICAgICAgICAyOCxcbiAgICAgICAgMjAzLFxuICAgICAgICAxMDYsXG4gICAgICAgIDExNyxcbiAgICAgICAgOTEsXG4gICAgICAgIDYxLFxuICAgICAgICA3MVxuICAgICAgXVxuICAgIH0sXG4gICAgXCJwdWJsaWNcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAxMTcsXG4gICAgICAgIDgwLFxuICAgICAgICAyMjYsXG4gICAgICAgIDEyNCxcbiAgICAgICAgNTQsXG4gICAgICAgIDMzLFxuICAgICAgICA1OCxcbiAgICAgICAgMTQzLFxuICAgICAgICAxNDcsXG4gICAgICAgIDIzNSxcbiAgICAgICAgMTE4LFxuICAgICAgICAwLFxuICAgICAgICAxNTUsXG4gICAgICAgIDUxLFxuICAgICAgICA0NyxcbiAgICAgICAgMTIsXG4gICAgICAgIDE1LFxuICAgICAgICAyMjUsXG4gICAgICAgIDE1NSxcbiAgICAgICAgMTk0LFxuICAgICAgICAzNCxcbiAgICAgICAgMTY1LFxuICAgICAgICA4MSxcbiAgICAgICAgMTY0LFxuICAgICAgICAxNDEsXG4gICAgICAgIDEzMSxcbiAgICAgICAgMjUwLFxuICAgICAgICA0NixcbiAgICAgICAgMTY4LFxuICAgICAgICAxNTIsXG4gICAgICAgIDE4MSxcbiAgICAgICAgMTA5XG4gICAgICBdXG4gICAgfVxuICB9LFxuICBcInNpZ25lZFByZUtleVwiOiB7XG4gICAgXCJrZXlQYWlyXCI6IHtcbiAgICAgIFwicHJpdmF0ZVwiOiB7XG4gICAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgICBcImRhdGFcIjogW1xuICAgICAgICAgIDg4LFxuICAgICAgICAgIDk0LFxuICAgICAgICAgIDEyOCxcbiAgICAgICAgICAyNDgsXG4gICAgICAgICAgMjQwLFxuICAgICAgICAgIDYyLFxuICAgICAgICAgIDEwOCxcbiAgICAgICAgICAyMzUsXG4gICAgICAgICAgNTAsXG4gICAgICAgICAgMTg2LFxuICAgICAgICAgIDE3MyxcbiAgICAgICAgICAxODYsXG4gICAgICAgICAgMTYyLFxuICAgICAgICAgIDQ4LFxuICAgICAgICAgIDE4NyxcbiAgICAgICAgICAzLFxuICAgICAgICAgIDQyLFxuICAgICAgICAgIDI0MCxcbiAgICAgICAgICA4MixcbiAgICAgICAgICA4NixcbiAgICAgICAgICAyOCxcbiAgICAgICAgICAyMDcsXG4gICAgICAgICAgNixcbiAgICAgICAgICAxOCxcbiAgICAgICAgICAyMTgsXG4gICAgICAgICAgMjEzLFxuICAgICAgICAgIDE2MCxcbiAgICAgICAgICAxMDgsXG4gICAgICAgICAgMTk3LFxuICAgICAgICAgIDExOSxcbiAgICAgICAgICAxNjcsXG4gICAgICAgICAgMTI3XG4gICAgICAgIF1cbiAgICAgIH0sXG4gICAgICBcInB1YmxpY1wiOiB7XG4gICAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgICBcImRhdGFcIjogW1xuICAgICAgICAgIDUwLFxuICAgICAgICAgIDE3NixcbiAgICAgICAgICAxNyxcbiAgICAgICAgICAzLFxuICAgICAgICAgIDE1OSxcbiAgICAgICAgICAyMjcsXG4gICAgICAgICAgOCxcbiAgICAgICAgICAxNjMsXG4gICAgICAgICAgMjAxLFxuICAgICAgICAgIDYxLFxuICAgICAgICAgIDI0MixcbiAgICAgICAgICAyMjcsXG4gICAgICAgICAgNTMsXG4gICAgICAgICAgMjQ3LFxuICAgICAgICAgIDExMyxcbiAgICAgICAgICAyMTYsXG4gICAgICAgICAgOTksXG4gICAgICAgICAgMTM2LFxuICAgICAgICAgIDg1LFxuICAgICAgICAgIDE1NCxcbiAgICAgICAgICAxNjUsXG4gICAgICAgICAgMjMwLFxuICAgICAgICAgIDE4NCxcbiAgICAgICAgICAxMjIsXG4gICAgICAgICAgNzksXG4gICAgICAgICAgMjE2LFxuICAgICAgICAgIDE3MCxcbiAgICAgICAgICAxNzgsXG4gICAgICAgICAgMTA1LFxuICAgICAgICAgIDQwLFxuICAgICAgICAgIDcsXG4gICAgICAgICAgM1xuICAgICAgICBdXG4gICAgICB9XG4gICAgfSxcbiAgICBcInNpZ25hdHVyZVwiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDE4MCxcbiAgICAgICAgMTIzLFxuICAgICAgICAxNSxcbiAgICAgICAgMTQ0LFxuICAgICAgICAxMixcbiAgICAgICAgOTAsXG4gICAgICAgIDY1LFxuICAgICAgICAxODksXG4gICAgICAgIDEzMixcbiAgICAgICAgMTY2LFxuICAgICAgICA0LFxuICAgICAgICAyNDMsXG4gICAgICAgIDIxOCxcbiAgICAgICAgMTk5LFxuICAgICAgICA4MSxcbiAgICAgICAgMjE1LFxuICAgICAgICAxMTIsXG4gICAgICAgIDY3LFxuICAgICAgICAyNDMsXG4gICAgICAgIDIyNSxcbiAgICAgICAgNTUsXG4gICAgICAgIDE0MCxcbiAgICAgICAgMTQ0LFxuICAgICAgICAyNTUsXG4gICAgICAgIDgwLFxuICAgICAgICAxNzcsXG4gICAgICAgIDE0MSxcbiAgICAgICAgMjEwLFxuICAgICAgICAxODQsXG4gICAgICAgIDE2OSxcbiAgICAgICAgNixcbiAgICAgICAgMjUzLFxuICAgICAgICAyNTUsXG4gICAgICAgIDExMCxcbiAgICAgICAgNSxcbiAgICAgICAgMTMwLFxuICAgICAgICAxNDYsXG4gICAgICAgIDEsXG4gICAgICAgIDE0MCxcbiAgICAgICAgNzIsXG4gICAgICAgIDEsXG4gICAgICAgIDIzNyxcbiAgICAgICAgODQsXG4gICAgICAgIDIxMCxcbiAgICAgICAgMTk0LFxuICAgICAgICAyMzgsXG4gICAgICAgIDIwNixcbiAgICAgICAgMTM4LFxuICAgICAgICAxMTQsXG4gICAgICAgIDIyOCxcbiAgICAgICAgNjEsXG4gICAgICAgIDE5NyxcbiAgICAgICAgMTUwLFxuICAgICAgICA2OCxcbiAgICAgICAgMTczLFxuICAgICAgICAxODAsXG4gICAgICAgIDIyNyxcbiAgICAgICAgODYsXG4gICAgICAgIDg5LFxuICAgICAgICAyMjQsXG4gICAgICAgIDE0MyxcbiAgICAgICAgMjUxLFxuICAgICAgICA4LFxuICAgICAgICAxMzlcbiAgICAgIF1cbiAgICB9LFxuICAgIFwia2V5SWRcIjogMVxuICB9LFxuICBcInJlZ2lzdHJhdGlvbklkXCI6IDU4LFxuICBcImFkdlNlY3JldEtleVwiOiBcIkNyZE9sZWNPYlVjRlBQZXFSUkJoV2hQS3VjQzNYNXh2YjVJRExSWUwxS0U9XCIsXG4gIFwicHJvY2Vzc2VkSGlzdG9yeU1lc3NhZ2VzXCI6IFtcbiAgICB7XG4gICAgICBcImtleVwiOiB7XG4gICAgICAgIFwicmVtb3RlSmlkXCI6IFwiOTIzNDgxNjYwNTgzQHMud2hhdHNhcHAubmV0XCIsXG4gICAgICAgIFwiZnJvbU1lXCI6IHRydWUsXG4gICAgICAgIFwiaWRcIjogXCIwMENGNUM0NTIzNzUzMUM2QTFCREUwOTIwNjAyNEQwRVwiXG4gICAgICB9LFxuICAgICAgXCJtZXNzYWdlVGltZXN0YW1wXCI6IDE3MTQ3MTE4NTVcbiAgICB9LFxuICAgIHtcbiAgICAgIFwia2V5XCI6IHtcbiAgICAgICAgXCJyZW1vdGVKaWRcIjogXCI5MjM0ODE2NjA1ODNAcy53aGF0c2FwcC5uZXRcIixcbiAgICAgICAgXCJmcm9tTWVcIjogdHJ1ZSxcbiAgICAgICAgXCJpZFwiOiBcIjE4OEU1MENDMDc3NkEwMDVCMjE5NUJGMTI0MDM4NEQ2XCJcbiAgICAgIH0sXG4gICAgICBcIm1lc3NhZ2VUaW1lc3RhbXBcIjogMTcxNDcxMTg1NVxuICAgIH1cbiAgXSxcbiAgXCJuZXh0UHJlS2V5SWRcIjogMzEsXG4gIFwiZmlyc3RVbnVwbG9hZGVkUHJlS2V5SWRcIjogMzEsXG4gIFwiYWNjb3VudFN5bmNDb3VudGVyXCI6IDEsXG4gIFwiYWNjb3VudFNldHRpbmdzXCI6IHtcbiAgICBcInVuYXJjaGl2ZUNoYXRzXCI6IGZhbHNlXG4gIH0sXG4gIFwiZGV2aWNlSWRcIjogXCJ2Wm5TYWFqVVJhZS1USU4tQ2tXd1lRXCIsXG4gIFwicGhvbmVJZFwiOiBcIjYzN2I5ZDZhLTJmYjAtNGYyYy1iZTM5LTQ3MmFkMjY2NjA5ZVwiLFxuICBcImlkZW50aXR5SWRcIjoge1xuICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgIFwiZGF0YVwiOiBbXG4gICAgICAxMzMsXG4gICAgICAxODEsXG4gICAgICAyNTEsXG4gICAgICA0NyxcbiAgICAgIDc2LFxuICAgICAgMTQ2LFxuICAgICAgMjM3LFxuICAgICAgMTcwLFxuICAgICAgNzQsXG4gICAgICAxNixcbiAgICAgIDI2LFxuICAgICAgMTY1LFxuICAgICAgMjM5LFxuICAgICAgMTIzLFxuICAgICAgOTIsXG4gICAgICA5NSxcbiAgICAgIDcxLFxuICAgICAgNTQsXG4gICAgICAxNzAsXG4gICAgICAxMDhcbiAgICBdXG4gIH0sXG4gIFwicmVnaXN0ZXJlZFwiOiB0cnVlLFxuICBcImJhY2t1cFRva2VuXCI6IHtcbiAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICBcImRhdGFcIjogW1xuICAgICAgMTc3LFxuICAgICAgMTMyLFxuICAgICAgMTA3LFxuICAgICAgMzMsXG4gICAgICAxNjcsXG4gICAgICA3MixcbiAgICAgIDI0MixcbiAgICAgIDI2LFxuICAgICAgMTM5LFxuICAgICAgNjYsXG4gICAgICA3MixcbiAgICAgIDIxMyxcbiAgICAgIDE4MSxcbiAgICAgIDEzNCxcbiAgICAgIDI0OSxcbiAgICAgIDUyLFxuICAgICAgMTQsXG4gICAgICA5NixcbiAgICAgIDM0LFxuICAgICAgMzlcbiAgICBdXG4gIH0sXG4gIFwicmVnaXN0cmF0aW9uXCI6IHt9LFxuICBcInBhaXJpbmdDb2RlXCI6IFwiS1JWUFE0UFBcIixcbiAgXCJtZVwiOiB7XG4gICAgXCJpZFwiOiBcIjkyMzQ4MTY2MDU4MzozQHMud2hhdHNhcHAubmV0XCIsXG4gICAgXCJsaWRcIjogXCIyMTcxODg0NDMxMTU2ODk6M0BsaWRcIixcbiAgICBcIm5hbWVcIjogXCJEalwiXG4gIH0sXG4gIFwiYWNjb3VudFwiOiB7XG4gICAgXCJkZXRhaWxzXCI6IFwiQ01LMnh5c1FxdHJSc1FZWUFpQUFLQUE9XCIsXG4gICAgXCJhY2NvdW50U2lnbmF0dXJlS2V5XCI6IFwiUEY5MVNQSzRhMzJnV0RrZnlmQ2c0TmUzbGpWRW1aU3JNYktmYSsrRjZ6cz1cIixcbiAgICBcImFjY291bnRTaWduYXR1cmVcIjogXCJxMjVsK3BGZW5OYy93NEpscXNGaGFtM1FjWXlvYkJ1MTg5alJOa1BzdW90YzREN2hYaDJvYklZaXlJQmVLUkwydlZVV2NhNWlvajZMalRMMC8zQjZEUT09XCIsXG4gICAgXCJkZXZpY2VTaWduYXR1cmVcIjogXCJpcTZ0NWNQR2xzV1BxNEdFK21GUFA2ODRJNW96eFRPTGVmN3M5c1BRY0Q2bkQ1Sm5aWU8yN0hTY0oyRHJRWC9Fa1FVSnhuUUtLaXdUNU1EL1U2TU1nQT09XCJcbiAgfSxcbiAgXCJzaWduYWxJZGVudGl0aWVzXCI6IFtcbiAgICB7XG4gICAgICBcImlkZW50aWZpZXJcIjoge1xuICAgICAgICBcIm5hbWVcIjogXCI5MjM0ODE2NjA1ODM6M0BzLndoYXRzYXBwLm5ldFwiLFxuICAgICAgICBcImRldmljZUlkXCI6IDBcbiAgICAgIH0sXG4gICAgICBcImlkZW50aWZpZXJLZXlcIjoge1xuICAgICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgICA1LFxuICAgICAgICAgIDYwLFxuICAgICAgICAgIDk1LFxuICAgICAgICAgIDExNyxcbiAgICAgICAgICA3MixcbiAgICAgICAgICAyNDIsXG4gICAgICAgICAgMTg0LFxuICAgICAgICAgIDEwNyxcbiAgICAgICAgICAxMjUsXG4gICAgICAgICAgMTYwLFxuICAgICAgICAgIDg4LFxuICAgICAgICAgIDU3LFxuICAgICAgICAgIDMxLFxuICAgICAgICAgIDIwMSxcbiAgICAgICAgICAyNDAsXG4gICAgICAgICAgMTYwLFxuICAgICAgICAgIDIyNCxcbiAgICAgICAgICAyMTUsXG4gICAgICAgICAgMTgzLFxuICAgICAgICAgIDE1MCxcbiAgICAgICAgICA1MyxcbiAgICAgICAgICA2OCxcbiAgICAgICAgICAxNTMsXG4gICAgICAgICAgMTQ4LFxuICAgICAgICAgIDE3MSxcbiAgICAgICAgICA0OSxcbiAgICAgICAgICAxNzgsXG4gICAgICAgICAgMTU5LFxuICAgICAgICAgIDEwNyxcbiAgICAgICAgICAyMzksXG4gICAgICAgICAgMTMzLFxuICAgICAgICAgIDIzNSxcbiAgICAgICAgICA1OVxuICAgICAgICBdXG4gICAgICB9XG4gICAgfVxuICBdLFxuICBcInBsYXRmb3JtXCI6IFwiYW5kcm9pZFwiLFxuICBcImxhc3RBY2NvdW50U3luY1RpbWVzdGFtcFwiOiAxNzE0NzExODUzLFxuICBcIm15QXBwU3RhdGVLZXlJZFwiOiBcIkFBQUFBSFZ5XCJcbn0iLAogICJhcHAtc3RhdGUtc3luYy1rZXktQUFBQUFIVnkuanNvbiI6ICJ7XCJrZXlEYXRhXCI6XCJrWFJ1NkN0WDFNRlJMbjhFRkpBL0dyeEY1MG5LempERXJwamRLQ21SYTZFPVwiLFwiZmluZ2VycHJpbnRcIjp7XCJyYXdJZFwiOjkxMzQ3Nzc4LFwiY3VycmVudEluZGV4XCI6MSxcImRldmljZUluZGV4ZXNcIjpbMCwxXX0sXCJ0aW1lc3RhbXBcIjpcIjE3MTQ1MjY5NjY5OTZcIn0iCn0=",  // PUT SESSION ID HERE 
  errorChat : process.env.ERROR_CHAT || "",
  KOYEB_API : process.env.KOYEB_API  || "false",

  REMOVE_BG_KEY : process.env.REMOVE_BG_KEY  || "",
  OPENAI_API_KEY: process.env.OPENAI_API_KEY || "",
  HEROKU_API_KEY: process.env.HEROKU_API_KEY || "",
  HEROKU_APP_NAME:process.env.HEROKU_APP_NAME|| "",
  antilink_values:process.env.ANTILINK_VALUES|| "all",
  HEROKU: process.env.HEROKU_APP_NAME && process.env.HEROKU_API_KEY,

  aitts_Voice_Id : process.env.AITTS_ID || "37",
  ELEVENLAB_API_KEY: process.env.ELEVENLAB_API_KEY || "",
  WORKTYPE: process.env.WORKTYPE||process.env.MODE || "private",
  LANG: process.env.THEME ? process.env.THEME.toUpperCase() : "SUHAIL",



};




























global.isMongodb = false; 
let file = require.resolve(__filename)
fs.watchFile(file, () => { fs.unwatchFile(file);console.log(`Update'${__filename}'`);delete require.cache[file];	require(file); })
 

// ========================= [ Disables in V.1.2.8 ] ===============================\\  
  //style : process.env.STYLE || "2",  // put '1' & "2" here to check bot styles
  //readmessage:process.env.READ_MESSAGE|| "false",
  //warncount: process.env.WARN_COUNT || 3,
  //userImages:process.env.USER_IMAGES|| "text",  // SET IMAGE AND VIDEO URL FOR BOT MENUS 
  //disablepm: process.env.DISABLE_PM || "false",
  //MsgsInLog: process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
  //readcmds:process.env.READ_COMMANDS|| "false", 
  //alwaysonline:process.env.WAPRESENCE|| "unavailable", // 'unavailable' | 'online' | 'composing' | 'recording' | 'paused'
  //read_status: process.env.AUTO_READ_STATUS || "false",
  //save_status: process.env.AUTO_SAVE_STATUS || "false",
 
